name = "datadump"
version = "0.1.0"

[dependencies]
cicd = "0.9.2"
distrib = "0.9.2"
fs = "0.9.2"
http = "0.9.2"
log = "0.9.2"
net = "0.9.2"
process = "0.9.2"
std = "0.9.2"
work = "0.9.2"
sql = "0.9.2"

[entrypoints]
main = "datadump::main"
